package com.sbmtech.model;
public enum ERole {
	ROLE_MEMBER,
    ROLE_GROUP,
    ROLE_COMPANY,
    ROLE_ADMIN,
    ROLE_GROUP_ADMIN,
    ROLE_SALES,
    ROLE_DRAWING,
    ROLE_WORK,
    ROLE_MATERIAL,
    ROLE_PRICE,
    ROLE_PAYMENT,
    ROLE_ATTENDANCE,
    ROLE_DESIGN,
    ROLE_PURCHASE,
    ROLE_HR,
    ROLE_CASH
}